import React from 'react'
import { motion } from 'framer-motion'
import { Sparkles, AlertTriangle, TrendingUp, CheckCircle2 } from 'lucide-react'
import { useAIEda, STAGES } from '../../context/AIEdaContext'
import SectionHeader from '../../components/common/SectionHeader'
import { useNavigate } from 'react-router-dom'

function InsightCard({ insight, index }) {
  const severityColors = {
    High: 'border-l-rose-500',
    Moderate: 'border-l-amber-500',
    Low: 'border-l-blue-400',
  }
  const confidenceColors = {
    High: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    Moderate: 'bg-amber-100 text-amber-800 border-amber-300',
    Low: 'bg-slate-100 text-slate-600 border-slate-300',
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.06 }}
      className={`p-5 rounded-2xl bg-white border border-slate-200/90 shadow-sm border-l-4 ${severityColors[insight.severity || insight.confidence] || 'border-l-blue-400'}`}
    >
      {/* Observation */}
      <div className="flex items-start gap-2 mb-3">
        <TrendingUp className="w-4 h-4 text-blue-500 flex-shrink-0 mt-0.5" />
        <p className="text-sm font-bold text-slate-800">{insight.observation}</p>
      </div>

      {/* Evidence */}
      {insight.evidence && (
        <div className="ml-6 mb-2 p-2.5 rounded-lg bg-slate-50 border border-slate-200/80">
          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">Statistical Evidence</p>
          <p className="text-xs text-slate-700 font-mono">{insight.evidence}</p>
        </div>
      )}

      {/* Interpretation */}
      {insight.interpretation && (
        <div className="ml-6 mb-3">
          <p className="text-xs text-slate-600 leading-relaxed">{insight.interpretation}</p>
        </div>
      )}

      {/* Confidence Badge */}
      <div className="ml-6 flex items-center gap-2">
        <span className={`px-2 py-0.5 rounded-md text-[10px] font-bold border ${confidenceColors[insight.confidence] || confidenceColors.Low}`}>
          Confidence: {insight.confidence || 'Unknown'}
        </span>
      </div>
    </motion.div>
  )
}

export default function AIInsightsPage() {
  const { pipelineStage, aiPlan, isAiFallback } = useAIEda()
  const navigate = useNavigate()

  if (pipelineStage === STAGES.EMPTY) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center space-y-4">
        <p className="text-sm text-slate-500 font-medium">No dataset loaded.</p>
        <button onClick={() => navigate('/ai-eda')} className="px-4 py-2 rounded-xl bg-blue-600 text-white text-xs font-bold hover:bg-blue-500">
          Go to Overview & Upload
        </button>
      </div>
    )
  }

  if (pipelineStage !== STAGES.READY) {
    return <div className="py-20 text-center text-sm text-slate-400 font-medium">Processing dataset...</div>
  }

  const insights = aiPlan?.insights || []

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-8">
      <SectionHeader
        title="AI-Generated Insights"
        subtitle="Evidence-based observations, statistical findings, and analytical interpretations"
      />

      {isAiFallback && (
        <div className="p-3 rounded-xl bg-amber-50 border border-amber-200 text-xs text-amber-700 font-medium flex items-center gap-2">
          <AlertTriangle className="w-3.5 h-3.5" />
          Insights generated using local statistical analysis. Configure NVIDIA API key for AI-enhanced insights.
        </div>
      )}

      {!isAiFallback && (
        <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-xs text-emerald-700 font-medium flex items-center gap-2">
          <Sparkles className="w-3.5 h-3.5" />
          Insights generated by AI analysis. All findings are backed by statistical evidence from your data.
        </div>
      )}

      {insights.length === 0 ? (
        <div className="p-8 rounded-2xl bg-slate-50 border border-slate-200 text-center">
          <p className="text-sm text-slate-500 font-medium">No significant patterns detected.</p>
          <p className="text-xs text-slate-400 mt-1">The dataset may not contain enough variability for meaningful insights.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {insights.map((insight, idx) => (
            <InsightCard key={insight.id || idx} insight={insight} index={idx} />
          ))}
        </div>
      )}

      {/* Disclaimer */}
      <div className="p-4 rounded-xl bg-blue-50/60 border border-blue-200/60 text-xs text-blue-700">
        <div className="flex items-start gap-2">
          <CheckCircle2 className="w-4 h-4 text-blue-500 flex-shrink-0 mt-0.5" />
          <div>
            <p className="font-bold mb-0.5">Analytical Disclaimer</p>
            <p className="text-blue-600 leading-relaxed">
              All insights are based on statistical associations in the provided dataset. Correlation does not imply causation.
              Results should be validated with domain expertise before making decisions.
            </p>
          </div>
        </div>
      </div>
    </motion.div>
  )
}
